### ISSUE TITLE
Request for Tag: Component that represents a tag for labelling/categorizing using keywords.

### ISSUE THREAD

**Issue by AmirHussain93** [kyndryl-design-system/shidoka-applications#82] opened 2024-02-09 06:17 UTC
**Is your feature request related to a problem? Please describe.**
Yes

There is no Tag component available in shidoka as of now

**Describe the solution you'd like**
Would like to have a Tag Component

**Describe alternatives you've considered**
Using **cds-tag** from carbon design system at the moment.

**Additional context**

Screenshots attached
<img width="872" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/27803197/8d541dbf-01fc-4f93-b2de-2e124f2ffad3">

**Comment by brian-patrick-3** [comment] 2024-02-09 17:43
Closing as duplicate of #78

**Closed** 2024-02-09 17:43 UTC
Labels: duplicate
