### ISSUE TITLE
[Tooltip] Request for fixed position variant

### ISSUE THREAD

**Issue by ashishpawar12** [kyndryl-design-system/shidoka-applications#92] opened 2024-02-15 09:15 UTC
**Describe the bug**

when we added tooltip on data table for last row tooltip data table is adding some more space. 

**To Reproduce**

**Expected behavior**

Tooltip should show without taking table below space

**Screenshots**
<img width="1440" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/18259137/91057a57-6e40-43d4-b68b-df14441bb414">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment] 2024-02-15 14:50
This is expected behavior because the table has a internal scrollbar, and the tooltip uses absolute position. You could possibly mitigate this effect by changing the tooltip anchor position.

Alternatively, we could add a fixed position variant to the tooltip. That comes with a caveat where if you scroll the page or resize the window, the tooltip will not remain attached to the anchor. If you need this option, please respond yes and we will add it to the queue.

**Comment by ashishpawar12** [comment] 2024-02-16 03:31
Hi @brian-patrick-3 , Yes we need Fixed position variant same as overflow Menu for tooltip.

**Comment by brian-patrick-3** [comment] 2024-08-20 16:50
Closing this as all feature requests must go through AHA now.

**Closed by brian-patrick-3** 2024-08-20 16:50 UTC
Labels: enhancement, priority: low, size: medium
