### ISSUE TITLE
On-Input event isnt trigger for textInput component on close icon click

### ISSUE THREAD

**Issue by vaishnavi-dhakankar** [kyndryl-design-system/shidoka-applications#65] opened 2024-01-09 13:55 UTC
I am using the TextInput component on my page. I need to use the text value as a parameter. 
When I type in text on-Input event gets triggered. however when I click on the close (cross) icon the same event isn't triggered. 

Therefore am not able to use textInput as controlled  component as use it parameter for another event as its not getting clear when clear icon is clicked

**To Reproduce**

1. Add component kyn-text-input with an event on-input (print value)
2. add text in the input box
3. check the console log added in on-input event handler
4. click on close icon.
5. verify the text is cleared in textbox
6. cleck console - no console printed

**Expected behavior**
the event should be trigger on clear text icon

**Screenshots**

<img width="492" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/d5037957-287c-4510-a50d-f975f020b076">
<img width="496" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/455b5e63-171a-4419-943c-80c5709e2867">

https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/65853352-1b00-44bd-92e2-331916b88f9e

**Comment by brian-patrick-3** [comment] 2024-01-09 14:42
What version of shidoka-applications are you running? This was addressed in [version 1.1.11](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v1.1.11). If you try this in [our Storybook](https://kyndryl-design-system.github.io/shidoka-applications/?path=/story/components-text-input--text-input), you can see the `on-input` event gets triggered in the Actions tab when clicking the X.

**Comment by vaishnavi-dhakankar** [comment] 2024-01-10 06:47
I am using version 1.1.16 of shidoka-applications. I can see the event triggered on storybook however its not working in our react application

**Comment by brian-patrick-3** [comment] 2024-01-10 14:46
I tried this in our React sample app, and was unable to reproduce.

```js
import reactifyWc from 'reactify-wc';
import '@kyndryl-design-system/shidoka-applications/components/reusable/textInput';
const KynTextInput = reactifyWc('kyn-text-input');
```

```html
<KynTextInput on-on-input={(e) => console.log(e)}></KynTextInput>
```

`console.log` does output when clicking the X. 

I'm going to need some more information/code samples to reproduce your issue exactly, or if you could re-create this in [CodeSandbox](https://codesandbox.io/) or something that would be helpful.

**Comment by vaishnavi-dhakankar** [comment] 2024-01-10 15:34
It looks there is an issue with how we use the input event
We have been using it as on-input and onInput event, similar to how it's mentioned in the storybook code section. 
a.
` <kyn-text-input
   type="search"
   onInput={(_e) => onInputChange(_e)}
   value={searchText}
   placeholder={'search'}
/>`

b.with reactify component    
`import reactifyWc from 'reactify-wc';
const TextInput = reactifyWc('kyn-text-input')
<TextInput
   type="search"
   on-input={(_e) => onInputChange(_e)}
   value={searchText}
    placeholder={'search'}
/>`


Below is Shidoka storybook code
<img width="393" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/3fc79633-aaa4-4f74-982d-2e04f0feb463">

Sandbox example : [https://codesandbox.io/p/sandbox/shidoka-textbox-6w4jwz?file=%2Fsrc%2Findex.js%3A5%2C83](url)

**Comment by brian-patrick-3** [comment] 2024-01-10 15:38
Ah OK, the problem is that you are capturing the native `input` event bubbling up from the `<input>` element within `<kyn-text-input>`. You need to capture the custom `on-input` event instead.

**Closed by brian-patrick-3** 2024-01-10 15:38 UTC
Labels: not reproducible
