### ISSUE TITLE
Request for prop to hide/disable the Pin button in Local Nav

### ISSUE THREAD

**Issue by hbdevfrk** [kyndryl-design-system/shidoka-applications#59] opened 2024-01-01 13:05 UTC
I am evaluating using the Local Nav for a feature to be finished soon. Everything is okay except for one issue. 
I want to know if there is a way to hide the Collapse/Expand button of the Local Nav. 
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/155367390/ee7d345c-1e5a-42d6-8e4e-33eb5189a942)

There are issues which will prevent us with supporting the pinned + expanded state and therefore we want to not include this button initially.

**Comment by brian-patrick-3** [comment] 2024-01-01 22:33
Hiding the pin button is not possible currently. Can you provide any further details about your use case? It is intended to function like this. On hover, it opens over the page content. On pin, it pushes the page content. Take a look at the UI Shell component examples.

**Comment by hbdevfrk** [comment] 2024-01-02 08:30
We wanted to gradually adopt the component. Pin feature requires pushing the content, and we have a lot of pages which could get affected with pushing the content. 
So it would have been helpful if there is a parameter to hide the pin button.

**Comment by cunningham-kyndryl** [comment] 2024-01-03 16:33
@hbdevfrk  can you show what it looks like when the nav is open? Not fully understanding what the issue is. If the nav is pinned open, then the content surrounding the nav would already be there. So closing the nave and sliding content over would cause issues? Need more information to see if this is a wider problem for other teams too.

**Comment by hbdevfrk** [comment] 2024-01-05 08:57
Once component is used and inserted, the nav overlaps part of the content under it - both in hovered (but non-pinned) and pinned. The nav renders above the content.

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/155367390/b22f29b6-973b-4faa-9063-ed2047564650)

**Comment by marcosebastianlopez** [comment] 2024-03-05 22:43
Right now the local navigation is being updated for this release, we can look into perhaps implementing this request into the component. We'll update you here. Thank you!

**Comment by hbdevfrk** [comment] 2024-03-06 08:15
We ended up doing the necessary changes to support the pin button. So it is no longer a need for us right now but could be a good option to have for future usages of the component.
Thanks for the follow up.

Best,
Harshay Buradkar

Engineer, Business Services Software Engineering
Cloud Engineering & Kyndryl Bridge, Global CTO Office

+91 7558386874 Mobile
www.kyndryl.com<http://www.kyndryl.com>
[cid:164009b9-75c6-47e0-a80a-ca0cb48acb9d]
________________________________
From: Marco Sebastian Lopez ***@***.***>
Sent: Wednesday, March 6, 2024 4:13 AM
To: kyndryl-design-system/shidoka-applications ***@***.***>
Cc: HARSHAY Buradkar ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [kyndryl-design-system/shidoka-applications] Request for prop to hide/disable the Pin button in Local Nav (Issue #59)

Right now the local navigation is being updated for this release, we can look into perhaps implementing this request into the component. We'll update you here. Thank you! — Reply to this email directly, view it on GitHub, or unsubscribe. You
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/Dq81_Y1A2Q!d7OO-YBgb2_kf0_hqylYA2VW6xSbKRnZc_qBRL1yYm6LsNwDx66i1zIOdvx3GQqRJ0apummzP7HR8hdd_Mvmcsh-wgl3FpOCNSa_-PKDje7sYNMGuCaH12IOTOFYQNkgXw-sF919XmWADes$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Right now the local navigation is being updated for this release, we can look into perhaps implementing this request into the component. We'll update you here. Thank you!

**Closed** 2024-03-06 13:16 UTC
Labels: enhancement, design
